name: docs

on:
  push:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node setup
        uses: actions/setup-node@v1
        with:
          node-version: 17
          registry-url: "https://registry.npmjs.org"

      - name: Git setup
        run: |
          git config --global user.email "valflrt@pm.me"
          git config --global user.name "valflrt"

      - name: Clean install (using `npm ci`)
        run: npm ci

      - name: Generate docs
        run: npm run docs:gen

      - name: Update docs
        run: |
          git add docs/*
          git commit -a -m "Auto-update docs." && git push
